server:
  port: 8080

spring:
  config:
    import: optional:file:.env[.properties]
  data:
    redis:
      port: ${REDIS_PORT:.env}
      host: ${REDIS_HOST:.env}
      password: ${REDIS_PASSWORD:.env}
      timeout: 30000

logging:
  level:
    io.github.deppan: debug